spring.application.name=shopflow

spring.datasource.url=jdbc:postgresql://localhost:5432/shopflow
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=86400000

spring.profiles.active=local