spring.application.name=shopflow

spring.datasource.url=jdbc:postgresql://localhost:5432/shopflow
spring.datasource.username=shopflow_user
spring.datasource.password=shopflow_pass

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

jwt.secret=your_jwt_secret_key
jwt.expiration=86400000